# pre-commit runs static analysis in the CI for this repo
#
# you can also use it to have the static analysis run incrementally on your commits;
#
# install:
#
#     pip install .[test]
#     pre-commit install
#
# after this, pre-commit will run automatically when you run `git commit`; it will
# flag any answers, and in the case of black / isort will automatically update
# your local files
#
# run on the whole repo: pre-commit run --all-files
# run a single hook:     pre-commit run --all-files black
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: mixed-line-ending
      args: ['--fix=lf']
      description: Forces to replace line ending by the UNIX 'lf' character.

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake PEP8 check
        additional_dependencies: ["importlib-metadata<=4.13.0"]
        args: ["--max-line-length=120"]


  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
