# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
        pre-commit install
        pre-commit autoupdate
    - name: Lint with precommit checks
      run: |
        pre-commit run --all-files
    - name: Test with Pytest
      run: |
        pytest \
          --junitxml=junit/test-results.xml \
          --cov --cov-report=xml \
          tests/
    - name: Make coverage file
      run: |
        echo "## Coverage Report" >> $GITHUB_STEP_SUMMARY
        coverage report -m --format=markdown >> $GITHUB_STEP_SUMMARY

  python-compatibility:
    needs: unit-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "pypy3.11",]
        # skipping 3.13 since the unit-test job runs against it
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Test with Pytest
      run: |
        pytest

  numpy-compatibility:
    needs: unit-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        numpy-version: ["1.26.4", "2.2.4"]
        # skipping 3.13 since the unit-test job runs against it
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Run unit-tests with numpy ${{ matrix.numpy-version }}
      run: |
        pytest